FROM node:latest-alpine3

WORKDIR /src/app

# Copy package.json and package-lock.json (if present) first
COPY package*.json ./

# Install dependencies
RUN npm install 

# Copy the rest of the project
COPY . .

EXPOSE 9000

CMD ["npm","start"]


